### PR TITLE
Add support media files in API for basic entries.

### PR DESCRIPTION
**Pull request by shaliko**
By story #97999652

### CODE REVIEW

**Comment by rikonen** [comment]
Looks good. One more thing that could be considered is adding a free text field associated with the files that could be used by the user to add some kind of comment associated with the file.

**Comment by shaliko** [comment]
OK, no problem. Will add "note" field.

**Comment by rikonen** [comment]
`note` should also be available in the upload API?

**Comment by rikonen** [comment]
Oh sorry, it is there. Didn't first see it since it was using a bit different syntax.

**Comment by rikonen** [comment]
:+1:

**Pull request merged**
