### PR TITLE
updated create account api docs.

### PR DESCRIPTION
**Pull request by plouh**

### CODE REVIEW

**Comment by Locke23rus** [comment]
@plouh can you also describe responseClass, because there are no info about format of response

**Comment by Locke23rus** [comment]
But actually we return something else(new class?) that includes user & access token https://github.com/HeiaHeia/HeiaHeia/blob/master/app/controllers/api/v2/users_controller.rb#L37

**Comment by plouh** [comment]
This is now updated and returned resources documented properly

**Comment by rikonen** [comment]
This API was eventually not used.

**Pull request closed without merging**
